# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/d/Programs/CPlusLearning_Caizh

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/d/Programs/CPlusLearning_Caizh

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/Programs/CPlusLearning_Caizh/CMakeFiles /mnt/d/Programs/CPlusLearning_Caizh//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/Programs/CPlusLearning_Caizh/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named demo

# Build rule for target.
demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demo
.PHONY : demo

# fast build rule for target.
demo/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/build
.PHONY : demo/fast

Source/LeetCodeSolution.o: Source/LeetCodeSolution.cpp.o
.PHONY : Source/LeetCodeSolution.o

# target to build an object file
Source/LeetCodeSolution.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/Source/LeetCodeSolution.cpp.o
.PHONY : Source/LeetCodeSolution.cpp.o

Source/LeetCodeSolution.i: Source/LeetCodeSolution.cpp.i
.PHONY : Source/LeetCodeSolution.i

# target to preprocess a source file
Source/LeetCodeSolution.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/Source/LeetCodeSolution.cpp.i
.PHONY : Source/LeetCodeSolution.cpp.i

Source/LeetCodeSolution.s: Source/LeetCodeSolution.cpp.s
.PHONY : Source/LeetCodeSolution.s

# target to generate assembly for a file
Source/LeetCodeSolution.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/Source/LeetCodeSolution.cpp.s
.PHONY : Source/LeetCodeSolution.cpp.s

Source/main.o: Source/main.cpp.o
.PHONY : Source/main.o

# target to build an object file
Source/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/Source/main.cpp.o
.PHONY : Source/main.cpp.o

Source/main.i: Source/main.cpp.i
.PHONY : Source/main.i

# target to preprocess a source file
Source/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/Source/main.cpp.i
.PHONY : Source/main.cpp.i

Source/main.s: Source/main.cpp.s
.PHONY : Source/main.s

# target to generate assembly for a file
Source/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/Source/main.cpp.s
.PHONY : Source/main.cpp.s

Source/mathFcn.o: Source/mathFcn.cpp.o
.PHONY : Source/mathFcn.o

# target to build an object file
Source/mathFcn.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/Source/mathFcn.cpp.o
.PHONY : Source/mathFcn.cpp.o

Source/mathFcn.i: Source/mathFcn.cpp.i
.PHONY : Source/mathFcn.i

# target to preprocess a source file
Source/mathFcn.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/Source/mathFcn.cpp.i
.PHONY : Source/mathFcn.cpp.i

Source/mathFcn.s: Source/mathFcn.cpp.s
.PHONY : Source/mathFcn.s

# target to generate assembly for a file
Source/mathFcn.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/Source/mathFcn.cpp.s
.PHONY : Source/mathFcn.cpp.s

Source/nQueen.o: Source/nQueen.cpp.o
.PHONY : Source/nQueen.o

# target to build an object file
Source/nQueen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/Source/nQueen.cpp.o
.PHONY : Source/nQueen.cpp.o

Source/nQueen.i: Source/nQueen.cpp.i
.PHONY : Source/nQueen.i

# target to preprocess a source file
Source/nQueen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/Source/nQueen.cpp.i
.PHONY : Source/nQueen.cpp.i

Source/nQueen.s: Source/nQueen.cpp.s
.PHONY : Source/nQueen.s

# target to generate assembly for a file
Source/nQueen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/Source/nQueen.cpp.s
.PHONY : Source/nQueen.cpp.s

Source/testFcns.o: Source/testFcns.cpp.o
.PHONY : Source/testFcns.o

# target to build an object file
Source/testFcns.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/Source/testFcns.cpp.o
.PHONY : Source/testFcns.cpp.o

Source/testFcns.i: Source/testFcns.cpp.i
.PHONY : Source/testFcns.i

# target to preprocess a source file
Source/testFcns.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/Source/testFcns.cpp.i
.PHONY : Source/testFcns.cpp.i

Source/testFcns.s: Source/testFcns.cpp.s
.PHONY : Source/testFcns.s

# target to generate assembly for a file
Source/testFcns.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/Source/testFcns.cpp.s
.PHONY : Source/testFcns.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... demo"
	@echo "... Source/LeetCodeSolution.o"
	@echo "... Source/LeetCodeSolution.i"
	@echo "... Source/LeetCodeSolution.s"
	@echo "... Source/main.o"
	@echo "... Source/main.i"
	@echo "... Source/main.s"
	@echo "... Source/mathFcn.o"
	@echo "... Source/mathFcn.i"
	@echo "... Source/mathFcn.s"
	@echo "... Source/nQueen.o"
	@echo "... Source/nQueen.i"
	@echo "... Source/nQueen.s"
	@echo "... Source/testFcns.o"
	@echo "... Source/testFcns.i"
	@echo "... Source/testFcns.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

